### ISSUE TITLE
Cannot use page arrows on the bottom even when maximized

### ISSUE THREAD

**Issue by johnbrvc** [icpc/ICPC-Registration-System#4]
This should be recalculated as a percentage of the window so that it is always visible and usable.  The workaround is to just display more rows per page but of course when clicking on a team then going back it defaults back to 10 per row.
![Picture1](https://user-images.githubusercontent.com/5657363/160608170-0cc4d66e-1399-476e-90ea-e9d503ab7fd2.jpg)

**Comment by JoeTerlizzi** [comment]
ok
